### ISSUE TITLE
permalinks do not work

### ISSUE THREAD

**Issue by smenzer** [CleverCloud/clever-wordpress#1]
I followed the instructions to set up a wordpress site with clevercloud. I'm able to access the home page and admin areas, but the permalinks for posts do not work, as you can see here: https://id5-test-wp.cleverapps.io/

Is there a setting that needs to be adjusted someplace to fix this? As mentioned, I followed the instructions exactly, without modifying anything else yet.

Thanks!

**Comment by smenzer** [comment]
i don't think this is actually an issue with this repo...i'm having the same issue with bedrock directly, too.  closing this out.

**Comment by juliamrch** [comment]
Hi Scott, I haven't encountered this issue when rebuilding. I approved your merge request and I'm going to run some tests with both versions. Thanks for the feedback.
